### ISSUE TITLE
improve check for ecs instance profile propagation

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#258]
In #254 we have a TODO https://github.com/bottlerocket-os/bottlerocket-test-system/pull/254#discussion_r789919956

We should find a way to query the API to check for propagation since we can't know exactly how long to wait.

**Comment by ecpullen** [comment]
`list_instance_profiles_for_role` does not work. It shows the instance profile before it is usable by ec2. For rerunning on an error of ec2 `run_instances`, I can check to see if the error is an `InvalidParameterValue` and then rerun, but it is possible that something else could cause that error.

**Comment by webern** [comment]
>  I can check to see if the error is an InvalidParameterValue and then rerun, but it is possible that something else could cause that error

That seems fine as long as the retries are bounded to a reasonable amount of time, e.g. timing out after retrying for a minute or so.
