### ISSUE TITLE
integrate with internal bottlerocket release process

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#267]
Let's use testsys for something!

There won't be any PR associated with the, but we will close it once testsys has found its way into the Bottlerocket release process.

Tracking:
- [x] Bug Fixes
  - [x] #314
  - [x] #313
  - [x] #312
  - [x] #328
  - [x] #332
  - [x] #314
  - [x] #325
  - [x] #327
  - [x] #339
  - [x] #353  
- [x] Ergonomic Improvements
  - [x] #79
  - [x] #298
  - [x] #304 
  - [x] #324
  - [x] #323
  - [x] #326
  - [x] #329
  - [x] #331
- [ ] Support all Variants and Test Modalities
  - [x] #315 
  - [x] #316 
  - [x] #317
  - [x] #318
  - [ ] #319

**Comment by webern** [comment]
Unfortunately #288 is blocking progress on this right now.

**Comment by webern** [comment]
#290 unblocks progress on this.

**Comment by webern** [comment]
Currently blocked by #313 

We can consider making the `sonobuoy retrieve` part optional and simply not doing it for now to unblock progress. That is, if we can't figure out the cause quickly.

**Comment by webern** [comment]
We have unblocked this by eliminating the tar ball retrieving functionality for now.

**Comment by mjsterckx** [comment]
Since there is only one thing left, we can use #319 to track this.
