### ISSUE TITLE
build: go mod vendor is slow in some environments

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#288]
In some environments `go mod vendor` in the docker builds can take a very long time. This is currently blocking #267

**Comment by etungsten** [comment]
I wonder if we can try leveraging the go toolchain from the Bottlerocket SDK like we do for Bottlerocket proper, see:
https://github.com/bottlerocket-os/bottlerocket/blob/9749af9973e4494768c2fac563172c753b6bc011/Makefile.toml#L258-L268

The docker-go tool can be found here: https://github.com/bottlerocket-os/bottlerocket/blob/develop/tools/docker-go

**Comment by webern** [comment]
> The docker-go tool can be found here

Yes. In general we seem to not have this problem for other builds including Bottlerocket, so we need to figure out what we are doing differently here.

**Comment by webern** [comment]
With #290 this is no longer blocking so I will change the labels and milestone assignment.

**Comment by webern** [comment]
This is addressed by #389, closing.
