### ISSUE TITLE
Add upgrade-downgrade flag to aws-k8s, aws-ecs and vmware-k8s commands

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#292]
We need to be able to run upgrade downgrade tests easily with the testsys cli.

When we give the upgrade-downgrade flag, a series of tests that depend on each other should be created (along with the resources that all of them depend on)

- initial sonobuoy check
- migrate to upgrade version
- sonobuoy upgrade version check
- migrate back to original version
- sonobuoy original version check

Some additional arguments will be required e.g.
- --starting-version
- --upgrade-version
- --tuf-repo-metadata-url
- --tuf-repo-targets-url

**Comment by ecpullen** [comment]
Closed by #297
