### ISSUE TITLE
cli: testsys status should report waiting

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#298]
If a test is waiting for resources before starting, testsys status reports the test as `starting`. Instead, for each test we should do the extra work to find out if it depends on resources and, if it does, to say that it is `waiting`.

Maybe the controller should write this to the CRD object so that testsys isn't making too many calls?

**Comment by ecpullen** [comment]
I would prefer the controller marking the test as waiting. We may also want to think about what status a test should have if one of the resources/tests that it depends on has failed/errored.

**Comment by webern** [comment]
> I would prefer the controller marking the test as waiting. We may also want to think about what status a test should have if one of the resources/tests that it depends on has failed/errored.

Sounds good. Let's see how complicated it is.
