### ISSUE TITLE
cli: dedup code in aws-k8s, vmware-k8s and aws-ecs commands

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#303]
I think we should come back to this rather than trying to address it here. I think there is an opportunity to use some traits or cleverness to refactor in a way that deduplicates the code a bit more between the `vmware-k8s`, `aws-k8s` and `ecs` commands. It's tricky because of all the strongly typed entities (structopt and our own config structs). We should look into it a bit when we have a chance.

_Originally posted by @webern in https://github.com/bottlerocket-os/bottlerocket-test-system/issues/297#issuecomment-1040775360_

**Comment by webern** [comment]
I think this may be addressed by #384

**Comment by ecpullen** [comment]
`bottlerocket/testsys` will be removed from the repo in the near future.
