### ISSUE TITLE
timeout waiting for terminated state but instances have terminated

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#327]
I have seen the following EC2 provider error:

x86-64-aws-k8s-121-nvidia-instances

Provider error: An error occurred but no resources were left behind, Timed-out waiting for instances to reach the `terminated` state.: deadline has elapsed

And yet, these instances do seem to have been terminated

![image](https://user-images.githubusercontent.com/6260372/155674491-653faac9-f9bb-4a13-9e9f-4d095986b763.png)

**Comment by webern** [comment]
This seems like a weird error stack:

```
bash-4.2$ isengard 359404537045 Administrator exec -- kubectl logs x86-64-aws-k8s-121-nvidia-instances-destruction-64nr4
[2022-02-28T01:56:05Z ERROR resource_agent::agent] Unable to obtain resource config from Kubernetes: Request failed: Unable to get resource: ApiError: resources.testsys.bottlerocket.aws "x86-64-aws-k8s-121-nvidia" not found: NotFound (ErrorResponse { status: "Failure", message: "resources.testsys.bottlerocket.aws \"x86-64-aws-k8s-121-nvidia\" not found", reason: "NotFound", code: 404 })
Provider error: An error occurred but no resources were left behind, Timed-out waiting for instances to reach the `terminated` state.: deadline has elapsed
```

Edit: I wonder if ignoring `404`s would fix this.

**Comment by etungsten** [comment]
See https://github.com/bottlerocket-os/bottlerocket-test-system/issues/337#issuecomment-1054495899

**Comment by webern** [comment]
Closing as likely dup of #337
