### ISSUE TITLE
oidc test failures (cli kubernetes version argument)

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#338]
When testing k8s 1.21 (either arch, with or without ipv6, and including the nvidia variant), we consistently see:

```
[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
```

If we kubectl exec into the test-agent and use sonobuoy to rerun failed, it passes. Currently we believe this is only occurring when we test using TestSys.

I found these issues, but they are old:
- https://github.com/kubernetes/kubernetes/issues/99480
- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/542

One of those mentions setting ` "--service-account-issuer": "https://kubernetes.default.svc.cluster.local",`

I don't see this in our configs:
- https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kubernetes-1.21/kubelet-config
- https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kubernetes-1.21/kubelet-exec-start-conf

But... it seems like we never needed it until the testsys agent was the one executing the sonobouy run command.

**Comment by webern** [comment]
I had a theory about this. I believe in testsys we are giving sonobuoy a kubernetes version that looks like this: `v1.21`. However in previous testing scripts, we discovered that we should give sonobuoy the exact/precise version of kubernetes that the control plane is running, e.g. `v1.21.7` (whatever it is).

It looks like this in the scripts:

```sh
#return cluster version from the kubeconfig file
get_cluster_version() ( set -euo pipefail

  local KUBECONFIG="${1:?must specify KUBECONFIG for the cluster}"
  local CLUSTER_VERSION=$(kubectl --kubeconfig "${KUBECONFIG}" version \
    --short --output json | jq -r '.serverVersion.gitVersion')

  echo "${CLUSTER_VERSION}" | awk -F - '{ print $1 }'
)
```

Being more precise with the kubernetes version *might* solve this pesky test failure. I can attest that I have seen a pesky test failure in the past when my kubernetes version argument was not precise enough.

**Comment by etungsten** [comment]
If you don't pass the kubernetes version to sonobuoy, sonobuoy itself would be able to figure out the cluster k8s version and use the correct k8s conformance test image. I would try leaving out the k8s image version override and try.

**Comment by webern** [comment]
The CLI argument is optional: https://github.com/bottlerocket-os/bottlerocket-test-system/blob/ae3b98b57d175c60f84b74f6f186f42f94efb1a3/testsys/src/run_aws_k8s.rs#L52

Eks Cluster config takes a Kubernetes version input, optionally and we pass through the option that we got from the command line
https://github.com/bottlerocket-os/bottlerocket-test-system/blob/ae3b98b57d175c60f84b74f6f186f42f94efb1a3/testsys/src/run_aws_k8s.rs#L336

The sonobuoy agent takes the k8s version optionally and also gets the option from the command line
https://github.com/bottlerocket-os/bottlerocket-test-system/blob/ae3b98b57d175c60f84b74f6f186f42f94efb1a3/testsys/src/run_aws_k8s.rs#L441

So to test this theory apparently all we have to do is remove our `--kubernetes-version` argument from our calls to testsys.

**Comment by webern** [comment]
Double checked here as well and looks like an Option::None will result in us leaving this argument out when calling sonobuoy.

https://github.com/bottlerocket-os/bottlerocket-test-system/blob/ae3b98b57d175c60f84b74f6f186f42f94efb1a3/bottlerocket-agents/src/sonobuoy.rs#L48..L58

**Comment by webern** [comment]
Update, through experimentation we believe that leaving the k8s version out when invoking sonobuoy does correct the OIDC failures.

The remaining thing to consider is whether we should change the CLI argument. It's confusing because
- In the case that `--kubernetes-version` is specificied and an EKS cluster is being created, it will be used in the eksctl create cluster call
- In the case that `--kubernetes-version` is specificed and an EKS cluster is *not* being created, it will be ignored by the eks provider.
- In all cases `--kubernetes-version` will be passed to sonobuoy if specified.

What we should probably do is add an argument like `--eks-cluster-creation-version` which only affects the eks-provider when it is creating a cluster. The argument can be documented since it's kind of weird that it will have no affect when the eks provider is re-using an existing cluster.

The `--kubernetes-version` argument exactly matches the name of the sonobuoy currently. We could consider renaming it to something ridiculous like `--sonobuoy-kubernetes-conformance-version`, or keep the name as is. Either way we should document that it is passed to sonobuoy, but that sonobuoy usually works best when left unspecified.
