### ISSUE TITLE
resource-provider: vmware cluster provider

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#35]
Support the creation and deletion of a VMware k8s cluster. Demonstrate a Sonobuoy test run that creates and destroys an EKS cluster, and uses the VMWare instance provider.

- depends on #32
- depends on #33

`id: vmware_cluster_provider`

**Comment by etungsten** [comment]
Re-opening this issue since we can use `eksctl-anywhere` to provision K8s clusters in vsphere that runs Bottlerocket for all the control plane components.

**Comment by etungsten** [comment]
`eksctl-anywhere` depends on docker to run commands in a container that contains the tooling it needs for preflight checks and Cluster API vSphere (CAPV) like `govc`, `clusterctl` etc. The resource agent would need to run in a privileged docker-in-docker container.

I've created a draft PR to allow configuring securitycontext.privileged for agent containers: https://github.com/bottlerocket-os/bottlerocket-test-system/pull/584.
