### ISSUE TITLE
cli: move to bottlerocket repo

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#369]
We are going to move the testsys CLI to the Bottlerocket repository for tight integration with the Bottlerocket build workflow. See https://github.com/bottlerocket-os/bottlerocket/issues/1419

We need to:

- [x] #366
- [x] #367 Make almost everything about the testsys CLI available in a lib.rs file
- [x] #368
- [x] #53
- [x] #438

**Comment by ecpullen** [comment]
The legacy `bottlerocket/testsys` cli has been removed, so this issue is done.
