### ISSUE TITLE
allow cluster creation without iam create role permissions

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#379]
IAM create role is a permission that we should be extremely protective of. We should make it possible to avoid assigning this role to testsys nodes and containers. There are some related roles that we probably want to avoid such as "attach role to instance profile"

This applies to
- [x] The EKS provider
- [x] The ECS provider

On the EKS side this is related to
- #225 because a configuration file would probably be used to pass the preexisting role
- #252 because it might also involve a configuration file
- #218 because we should provide instructions for the minimal set of permissions for various roles the system needs

There may be a more direct reference in eksctl documentation, but when I was searching I found an example here where it appears the role was created before the eksctl create cluster call:

https://reece.tech/posts/building-eks-clusters-using-eksctl/

A complication to consider: the EKS provider has logic for finding roles based on eksctl's naming convention.

**Comment by ecpullen** [comment]
This was closed with #447.
