### ISSUE TITLE
eks provider: set up aws config map

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#416]
We need to be able to add desired roles and users to the AwsConfig map when we create an EKS cluster. For example, if the testsys agents themselves are running on EKS, then the target EKS clusters need to allow control from the testsys cluster node's role.

This might be related to #225

**Comment by ecpullen** [comment]
This pr: https://github.com/weaveworks/eksctl/pull/5464 allows that level of configuration in the config file.
