### ISSUE TITLE
workload test cli

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#418]
We want to make it easy for developers to create tests that run as workloads on Bottlerocket: see #419 for more details.

This issue represents a CLI that can be used within the workload to make the workload test compatible with a sonobuoy plugin and with our equivalent implementation for ECS. The primary purpose of the CLI will be to write test successes and failures in the appropriate [format](https://github.com/vmware-tanzu/sonobuoy/blob/v0.18.0/pkg/client/results/processing.go#L91-L100) and location.

For example:

```shell
# try something in the workload running on the bottlerocket host
if success; then
    workload success "foo-test"
else
   workload failure "foo-test"
fi
```

**Comment by stmcginnis** [comment]
@ecpullen do we need a new CLI for this? Or would we be able to leverage https://github.com/bottlerocket-os/bottlerocket-test-system/pull/487 for this use?

**Comment by ecpullen** [comment]
This would be a cli that is run from within a pod from either a sonobuoy plugin or ecs task. It would likely need to be a new cli.

**Comment by ecpullen** [comment]
With the current setup for workload tests, this isn't needed anymore.
