### ISSUE TITLE
workload test agent

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#419]
Create a test agent for running container workloads on Bottlerocket. This test agent should take a generic configuration that is appropriate for both ECS and K8S so that we can run the same workload on `aws-ecs-*` and `*-k8s-*` variants of Bottlerocket.

When targeting a k8s variant, the agent will:
- create a sonobuoy plugin configuration that will run the workload
- within the workload, #418 will write test result information in a sonobuoy appropriate way
- the test agent will collect and report the results using the sonobuoy binary

When targeting an ecs variant, the agent will:
- create and run the workload as an ECS task
- within the workload, #418 will write test result information in a way that we want
- the test agent will collect and report the results in a bespoke manner

- [x] #616 
- [x] #617

depends on:
- #418

Here is some writing I did elsewhere to communicate the idea of a "workload test":

---

### Workload Tests

There is another class of test which we will call *Workload Tests*. Workload tests run a pod or task on Bottlerocket by way of the container orchestrator. Currently, we test Bottlerocket with Sonobuoy’s e2e conformance test suite. This is a workload test. 

For a workload test, the TestSys Test Agent launches a pod or task into the target cluster (the cluster where Bottlerocket nodes to be tested are running). The test code will run on a Bottlerocket node in the target cluster. For example, the NVIDIA smoke test will be launched into a K8s or ECS cluster where it will check that Tensorflow is working with GPU support. Essentially the same test will be valid for aws-ecs-1-nvidia as aws-k8s-1.21-nvidia. It is only the language with which the pod/task is specified that differs.

# Workload Tests for Bottlerocket

Workload tests run K8s pods or ECS task on Bottlerocket instances. They help ensure that the container orchestrator (kubelet or ecs-agent) is able to do its thing properly on Bottlerocket. Currently, we run Sonobuoy's "e2e" "plugin" to ensure k8s variance are compliant. We run an test suite to qualify the ECS variant, this is also a workload test.

We run sonobuoy "e2e" in "quick" mode and we run a simple ECS task for upgrade downgrade testing. These are *workload* tests. (Interestingly the actual process of updating the instance is modeled currently as an OS test.) We propose modeling Bottlerocket workload tests as custom sonobuoy plugins for K8s, and making a similar mechanism for ECS.

![bottlerocket-test-types drawio workload-test](https://user-images.githubusercontent.com/6260372/169919192-4d820337-3acf-4d6d-8e74-31e0acd80ac6.png)

## What is a Custom Sonobuoy Plugin

A custom sonobuoy plugin involves a container image that you create which Sonobuoy will run on the target K8s cluster. This container image can do whatever you want it to, as long as it conforms to a certain output format for reporting results. The output format is basically a set of YAML files in a certain format that sonobuoy can read. To run your plugin, you define a YAML file that is kind of like a pod spec, but it is specific to sonobuoy. Then you can use the sonobuoy command line to launch your custom plugin and see its results.

## Common Interface for Bottlerocket

For Bottlerocket, we may want to run the same test image on ECS. This presents two problems to solve:

* A common interface, not specific to sonobuoy, K8s or ECS, for defining the workload
* A common mechanism for specifying results

I propose that we define a common configuration for the test whether it is to be run on K8s or ECS. Thus, instead of creating a Sonobuoy plugin YAML file, we would create something in our own format.

* When running on K8s, TestSys would generate the appropriate Sonobuoy YAML and use Sonobuoy to run and observe the test.
* When running on ECS, TestSys will generate the ECS task and use its own mechanism to observe the test results.

We want to make sure this is abstracted away from the test author, so we propose providing a binary that you can use in your test scripts without worrying about which platform you are running on. The script that you run as part of your workload container might look very similar to the script shown above in the OS Test section. This time, however, instead of communicating with testsys, the helper CLI will be writing output files appropriate for consumption by Sonobuoy or our own ECS observer.

## Components of a Workload Test

* You will create a script or Rust program that will run as a K8s pod or ECS task.
* You will build and push an image that includes your script or rust program and is designed to run on Bottlerocket and to prove something about it. (Maybe the bottlerocket-test-system Makefile can help here)
* You will run the workload test with the testsys CLI which takes arguments relating to your workload test (like its image URI) and creates the Test object in the testsys cluster.

**Comment by ecpullen** [comment]
Both ECS and K8s workload testing agents have been merged! Closing the issue.
