### ISSUE TITLE
controller: support exclusive access to bottlerocket nodes

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#429]
Similar to #428, when we start introducing certain special Bottlerocket tests, these tests may require exclusive access to a Bottlerocket host, or they may need to run on Bottlerocket hosts that have been reset or otherwise are in a state appropriate for a given test. This issue represents the expectation that there will be requirements expending what we have done in #428

Considered an extension of functionality that is more specialized in #428 and thus...

depends on
- #428

**Comment by ecpullen** [comment]
We could add a `conflicts_with` field to the agent that would prevent a `Resource` or `Test` from being created while the other resources still exist. We could then use the resource `DestructionPolicy` to automatically clean up instances once the test passes.

**Comment by webern** [comment]
Good thinking, however

> DestructionPolicy to automatically clean up instances once the test passes

`DestructionPolicy` governs what happens when a Resource is deleted from the cluster. I don't think we would want the Resource CRD to be deleted from the cluster by the controller. Instead there probably needs to be some new field(s) to explain to the controller that a certain resource needs its deletion phase run after a test passes without deleting the CRD from the cluster.

**Comment by ecpullen** [comment]
If that's the case we probably should remove this `TODO` https://github.com/bottlerocket-os/bottlerocket-test-system/blob/ad639a82440f0d1dae66e6e9306c24324f034d68/model/src/resource.rs#L217
