### ISSUE TITLE
bottlerocket-test-tools: update sonobuoy version to v0.56.0+

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket-test-system#452]
It would be nice to switch to the newer versions of sonobuoy to get the latest features. A lot has been added since v0.50.0 that are really useful. e.g. There is a new test mode for the E2E plugin, conformance-lite, that skips all of the most time-consuming tests which cuts down the test time from 1 hr and half to around 10-15 mins which will be super useful for CI usecases.

**Comment by webern** [comment]
This is a great new feature.

**Comment by webern** [comment]
We already ship 0.56+! Yay https://github.com/bottlerocket-os/bottlerocket-test-system/blob/021e8d69b13b7d05e79963a0ff3f1c5c1af10753/tools/Dockerfile#L135

I've already started on a version bump anyway so I may increase this to 0.56.7

**Comment by webern** [comment]
Actually, since we already have the feature we want in our version (0.56.4) I'm going to close this and hold off on updating the tools image.
