### ISSUE TITLE
cli: Switch from `clap` to `argh` crate for parsing command line arguments

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket-test-system#535]
Most of our CLIs use the `argh` crate for parsing command line input. The `cli` - umm - CLI, uses `clap` instead.

It would be good to convert this over to `argh` so we are consistent across our code.

**Comment by webern** [comment]
`clap` is more feature-rich and it has more downloads than argh. My impression is that clap is the de-facto standard library for robust CLIs. I wouldn't be in favor of this change, at least not with a feature and syntax comparison.

**Comment by webern** [comment]
I don't think we want to do this.
