### ISSUE TITLE
Align released agent images and TestSys version

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket-test-system#542]
The system requires that the agents use the same TestSys version as the client. There should be a way to programmatically ensure this happens.

Somewhere in model, the version of testsys should be available so users can determine the testsys version that is being used. This will be useful for determining the location of the released testing images.

**Comment by mjsterckx** [comment]
> Somewhere in model, the version of testsys should be available so users can determine the testsys version that is being used.

It seems like it would make the most sense for that function to reside in `model/src/constants.rs`, right?
