### ISSUE TITLE
TestManager: Better status filtering

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket-test-system#656]
If many tests are being run, there will be many columns in testsys status and not all are visible when using cargo make watch-test. A set of filtering methods should be implemented for the status command to limit status results.

Ideas:
* Crd type (Test, Resource)
* Build
* Running tests
* Finished tests
* Failed tests
* Unfinished tests

These new filters should probably be incorporated in the form of `SelectionParams`

**Comment by webern** [comment]
Maybe... we should think about whether the same could be done with `grep` though. I know this was a request from @bcressey but sometimes the best solution is a simple one, so I want to make sure we don't build grep inside of testsys.

**Comment by ecpullen** [comment]
This is a bigger picture issue than just status filtering. By expanding the `SelectionParams`, we can offer different delete methods as well i.e delete all passed tests.
