### ISSUE TITLE
TestManager: Make `status` more useful

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket-test-system#679]
The current `TestManager::status` provides an expandable table containing the crd names, state, and the number of passed and failed tests. This issue is to track potential enhancements and discuss other possible solutions.

- [x] #658 
- [x] #656 
- [x] Test updates while running
- [x] Show the status of the resource
- [x] Add more frequent updates for resource creation
  - [x] EKS resource provider
  - [x] EC2 resource provider
  - [x] vSphere k8s cluster resource provider
  - [x] vSphere vm resource provider
  - [x] ECS cluster provider
- [x] Regular status updates for tests
  - [x] sonobuoy
  - [x] workload

One potential improvement, is test results. While a test is running a user has no idea how many tests have passed, run, or still have to run. It would be nice if tests could send updates as a testing suite (`sonobuoy`) progresses.

Another place with room for improvement is resource creation. When a resource is running, the `status` reports running, and that's it. There is no insight to what the agent is doing. A field could be added to status that displays a brief explanation of what's happening in the agent. This would also provide insight to errors without having to read the agents logs.

If any of these proposals are worth looking into, I will create a separate issue for them.

**Comment by ecpullen** [comment]
> One potential improvement, is test results. While a test is running a user has no idea how many tests have passed, run, or still have to run. It would be nice if tests could send updates as a testing suite (sonobuoy) progresses.


To solve this, we could have a `send_test_run_start` function  in the `Client` that would create a new item in the `TestResults` array. Then another function `send_updated_test_results` would replace the last item in the `TestResults` array. Whichever test result is the last in a running test would be the `running` test and results would be updated at whatever pace the agent sent them. With this proposal, the original flow of agents sending results at the end is unchanged, but it enables continuous status reporting for tests.

Another option is to replace `send_test_results` with the proposed `send_updated_test_result` and force all agents to follow that flow of information.

**Comment by ecpullen** [comment]
> Another place with room for improvement is resource creation. When a resource is running, the status reports running, and that's it. There is no insight to what the agent is doing. A field could be added to status that displays a brief explanation of what's happening in the agent. This would also provide insight to errors without having to read the agents logs.

Most resource agents have a `current_status` field in their `ProductionMemo`. When creating the status table, the value for `current_status` could be added to a column. If a resource didn't have a `current_status` field, nothing would be printed.

**Comment by webern** [comment]
> To solve this, we could have a send_test_run_start function in the Client that would create a new item in the TestResults array. Then another function send_updated_test_results would replace the last item in the TestResults array.

Seems like we discussed this at length a while back. It sounds like a good idea to me. There was something I got hung up on about the trait interface at the time, but I'm sure it will work out as you describe.

> Most resource agents have a current_status field in their ProductionMemo. When creating the status table, the value for current_status could be added to a column. If a resource didn't have a current_status field, nothing would be printed.

It's a little bit of a mix of concerns between the `Memo`'s purpose being for the agent to manage it's own state, and the `current_status` now being used for user display. But I think it is fine and it is a quick solution. Nice idea.

**Comment by ecpullen** [comment]
This was completed with the above prs.
