### ISSUE TITLE
agents: metadata_url gets partially overwritten if it has no trailing "/"

### ISSUE THREAD

**Issue by mjsterckx** [bottlerocket-os/bottlerocket-test-system#762]
https://github.com/bottlerocket-os/bottlerocket-test-system/blob/838b5bbfca09c4c4864eb93491d32024156f64d5/bottlerocket/agents/src/tuf.rs#L76

This line joins the filename to the metadata_url, but if metadata_url doesn't end with "/", it overwrites everything after the last "/" in the path.

**Comment by webern** [comment]
because... https://github.com/servo/rust-url/issues/713
Which points to the URL spec, basically that's how URLs work https://jsdom.github.io/whatwg-url/#url=cGF0aDQvcGF0aDUvcGF0aDY=&base=aHR0cHM6Ly9leGFtcGxlLmNvbS9wYXRoMS9wYXRoMi9wYXRoMw==

**Comment by webern** [comment]
...basically this is surprising as a user and could lead to a lot of troubleshooting. So before we Url::parse we should check if the metadata base URL has a trailing slash. If it doesn't, we should add it.
